---
# tasks file for godot

# Need GCC >= 7 so no RHEL 7
- name: Install required packages (RPM)
  yum:
    name:
      - python3
      - python3-pip
      - libXcursor-devel
      - libXinerama-devel
      - libXrandr-devel
      - libXi-devel
      - libGL-devel
      - xorg-x11-server-devel
      - gcc
      - gcc-c++
      - gcc-go
      - clang
      - git
      - make
    state: present
  when:
    (ansible_distribution == 'RedHat') or
    (ansible_distribution == 'Fedora') or
    (ansible_distribution == 'CentOS')

- name: Install required python3 modules
  pip:
    executable: pip3
    name: scons

  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: Clone the godot engine
  git:
    repo: 'https://github.com/godotengine/godot.git'
    dest: "{{ git_checkout }}"
    version: 'master'
    force: true

# Comment out Werror which breaks the build. How is this in godot
- name: Patch SConstruct
  lineinfile:
    path: "{{ git_checkout }}/SConstruct"
    regexp: 'env.Append\(CCFLAGS\=\[\"\-Werror\"\]\)'
    line: '#env.Append(CCFLAGS=["-Werror"])'

- name: Create Godot HOME
  file:
    path: "{{ godot_home }}"
    state: directory
    mode: '0755'

# godot.linuxbsd.opt.tools.64
- name: Compile godot.linuxbsd.opt.tools.64
  command:
    cmd: /usr/local/bin/scons platform=linuxbsd target=release_debug {{ scons_flags }}
    creates: "{{ git_checkout }}/bin/godot.linuxbsd.opt.tools.64"
    chdir: "{{ git_checkout }}"

- name: Strip debug symbols from godot.linuxbsd.opt.tools.64
  command:
    cmd: strip "bin/godot.linuxbsd.opt.tools.64"
    chdir: "{{ git_checkout }}"
  when: (strip_debug | bool)

- name: Install godot.linuxbsd.opt.tools.64 in Godot HOME
  copy:
    src: "{{ git_checkout }}/bin/godot.linuxbsd.opt.tools.64"
    dest: "{{ godot_home }}/godot"
    remote_src: true
    mode: '0755'
  when: (install_godot | bool)

# godot.linuxbsd.opt.debug.64
- name: Compile godot.linuxbsd.opt.debug.64
  command:
    cmd: scons platform=linuxbsd tools=no target=release_debug "use_lto=yes" "progress=no" "debug_symbols=no" "LINKFLAGS=-fuse-ld=gold" "-j12"
    creates: "{{ git_checkout }}/bin/godot.linuxbsd.opt.debug.64"
    chdir: "{{ git_checkout }}"

- name: Strip debug symbols from godot.linuxbsd.opt.debug.64
  command:
    cmd: strip "bin/godot.linuxbsd.opt.debug.64"
    chdir: "{{ git_checkout }}"
  when: (strip_debug | bool)

- name: Install godot.linuxbsd.opt.debug.64 in Godot HOME
  copy:
    src: "{{ git_checkout }}/bin/godot.linuxbsd.opt.debug.64"
    dest: "{{ godot_home }}/godot-runner-debug"
    remote_src: true
    mode: '0755'
  when: (install_godot | bool)

# godot.linuxbsd.opt.64
- name: Compile godot.linuxbsd.opt.64
  command:
    cmd: scons platform=linuxbsd tools=no target=release "use_lto=yes" "progress=no" "debug_symbols=no" "LINKFLAGS=-fuse-ld=gold" "-j12" -Wno-error
    creates: "{{ git_checkout }}/bin/godot.linuxbsd.opt.64"
    chdir: "{{ git_checkout }}"

- name: Strip debug symbols from godot.linuxbsd.opt.64
  command:
    cmd: strip "bin/godot.linuxbsd.opt.64"
    chdir: "{{ git_checkout }}"
  when: (strip_debug | bool)

- name: Install godot.linuxbsd.opt.64 in Godot HOME
  copy:
    src: "{{ git_checkout }}/bin/godot.linuxbsd.opt.64"
    dest: "{{ godot_home }}/godot-runner"
    remote_src: true
    mode: '0755'
  when: (install_godot | bool)


# godot.linuxbsd.opt.tools.64
- name: Compile godot.linuxbsd.opt.tools.64
  command:
    cmd: scons platform=linuxbsd target=release_debug "use_lto=yes" "progress=no" "debug_symbols=no" "LINKFLAGS=-fuse-ld=gold" "-j12"
    creates: "{{ git_checkout }}/bin/godot.linuxbsd.opt.tools.64"
    chdir: "{{ git_checkout }}"

- name: Strip debug symbols from godot.linuxbsd.opt.tools.64
  command:
    cmd: strip "bin/godot.linuxbsd.opt.tools.64"
    chdir: "{{ git_checkout }}"
  when: (strip_debug | bool)

- name: Install godot.linuxbsd.opt.tools.64 in Godot HOME
  copy:
    src: "{{ git_checkout }}/bin/godot.linuxbsd.opt.tools.64"
    dest: "{{ godot_home }}/godot-headless"
    remote_src: true
    mode: '0755'
  when: (install_godot | bool)


# godot_server.linuxbsd.opt.64
#- name: Compile godot_server.linuxbsd.opt.64
#  command:
#    cmd: scons platform=linuxbsd tools=no target=release "use_lto=yes" "progress=no" "debug_symbols=no" "LINKFLAGS=-fuse-ld=gold" "-j12"
#    creates: "{{ git_checkout }}/bin/godot_server.linuxbsd.opt.64"
#    chdir: "{{ git_checkout }}"
#
#- name: Strip debug symbols from godot_server.linuxbsd.opt.64
#  command:
#    cmd: strip "bin/godot_server.linuxbsd.opt.64"
#    chdir: "{{ git_checkout }}"
#  when: (strip_debug | bool)
#
#- name: Install godot_server.linuxbsd.opt.64 in Godot HOME
#  copy:
#    src: "{{ git_checkout }}/bin/godot_server.linuxbsd.opt.64"
#    dest: "{{ godot_home }}/godot-server"
#    remote_src: true
#    mode: '0755'
#  when: (install_godot | bool)
